// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL5lw5jQrovjxenvh0F5VdbE0hoL9AeOI',
    appId: '1:813636585639:web:d0df7d5577927687d43382',
    messagingSenderId: '813636585639',
    projectId: 'mycoffee-f5173',
    authDomain: 'mycoffee-f5173.firebaseapp.com',
    storageBucket: 'mycoffee-f5173.appspot.com',
    measurementId: 'G-Y2DJ6WEMMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDX7dcRB_0vh230eixygnBi2JSto-z7M4',
    appId: '1:813636585639:android:542e662f32d7f7b1d43382',
    messagingSenderId: '813636585639',
    projectId: 'mycoffee-f5173',
    storageBucket: 'mycoffee-f5173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNS7L2DBLkERz5iHDtjkuibZvsEfZgg1E',
    appId: '1:813636585639:ios:bd1f2a24efedd525d43382',
    messagingSenderId: '813636585639',
    projectId: 'mycoffee-f5173',
    storageBucket: 'mycoffee-f5173.appspot.com',
    iosClientId: '813636585639-ovi77vfsfvhf9b1nk5pu3hr0cdlm3l76.apps.googleusercontent.com',
    iosBundleId: 'com.example.mycoffee',
  );
}
